# To run: conda env create -f environment.yml
name: nerf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyterlab
  - pytorch==1.7.0
  - torchvision==0.8.1
  - numpy
  - imageio
  - matplotlib
  - scikit-image
  - black
