# To run: conda env create -f environment.yml
name: nerf

dependencies:
    - python=3.7
    - pip
    - tensorflow-gpu==1.15
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - imagemagick
