name: Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Check conda version
      run: |
        conda --version
        conda activate /anaconda3/envs/my_env

    - name: Install conda
      run: |
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x Miniconda3-latest-Linux-x86_64.sh
        ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"


    - name: Set up conda
      run: |
        export PATH="$HOME/miniconda3/bin:$PATH"
        echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
        conda init bash
        source ~/.bashrc

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure conda environment
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda activate nerf
        
    - name: Install Dependencies
      run: |
        conda env create -f environment.yml
        conda activate nerf
        pip install pylint
        
    - name: Run Pylint
      run: |
        pylint tiny_nerf.ipynb
